extensions:

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["0.0.0.0:8888"]

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:

processors:
  attributes:
    actions:
      - key: cluster
        value: eu-west-1
        action: upsert

  metricstransform:
    transforms:
      - include: otelcol_process_uptime
        action: update
        operations:
          - action: add_label
            new_label: cluster
            new_value: eu-west-1

exporters:
  jaeger:
    endpoint: localhost:15250
    insecure: true
  prometheus:
    endpoint: localhost:9090

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [metricstransform]
      exporters: [prometheus]
    traces:
      receivers: [jaeger]
      processors: [attributes]
      exporters: [jaeger]
